using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Sudoku.SolverLogic;

namespace Sudoku
{
    class ApplicationBuilder
    {
        private MainViewModel mainViewModel;
        public ApplicationBuilder(object dataContext)
        {
            mainViewModel = (MainViewModel)dataContext;
            
            mainViewModel.Solver = new SolverLogicContainerCompare();

            Field field1 = new Field(1);
            Field field2 = new Field(2);
            Field field3 = new Field(3);
            Field field4 = new Field(4);
            Field field5 = new Field(5);
            Field field6 = new Field(6);
            Field field7 = new Field(7);
            Field field8 = new Field(8);
            Field field9 = new Field(9);
            Field field10 = new Field(10);
            Field field11 = new Field(11);
            Field field12 = new Field(12);
            Field field13 = new Field(13);
            Field field14 = new Field(14);
            Field field15 = new Field(15);
            Field field16 = new Field(16);
            Field field17 = new Field(17);
            Field field18 = new Field(18);
            Field field19 = new Field(19);
            Field field20 = new Field(20);
            Field field21 = new Field(21);
            Field field22 = new Field(22);
            Field field23 = new Field(23);
            Field field24 = new Field(24);
            Field field25 = new Field(25);
            Field field26 = new Field(26);
            Field field27 = new Field(27);
            Field field28 = new Field(28);
            Field field29 = new Field(29);
            Field field30 = new Field(30);
            Field field31 = new Field(31);
            Field field32 = new Field(32);
            Field field33 = new Field(33);
            Field field34 = new Field(34);
            Field field35 = new Field(35);
            Field field36 = new Field(36);
            Field field37 = new Field(37);
            Field field38 = new Field(38);
            Field field39 = new Field(39);
            Field field40 = new Field(40);
            Field field41 = new Field(41);
            Field field42 = new Field(42);
            Field field43 = new Field(43);
            Field field44 = new Field(44);
            Field field45 = new Field(45);
            Field field46 = new Field(46);
            Field field47 = new Field(47);
            Field field48 = new Field(48);
            Field field49 = new Field(49);
            Field field50 = new Field(50);
            Field field51 = new Field(51);
            Field field52 = new Field(52);
            Field field53 = new Field(53);
            Field field54 = new Field(54);
            Field field55 = new Field(55);
            Field field56 = new Field(56);
            Field field57 = new Field(57);
            Field field58 = new Field(58);
            Field field59 = new Field(59);
            Field field60 = new Field(60);
            Field field61 = new Field(61);
            Field field62 = new Field(62);
            Field field63 = new Field(63);
            Field field64 = new Field(64);
            Field field65 = new Field(65);
            Field field66 = new Field(66);
            Field field67 = new Field(67);
            Field field68 = new Field(68);
            Field field69 = new Field(69);
            Field field70 = new Field(70);
            Field field71 = new Field(71);
            Field field72 = new Field(72);
            Field field73 = new Field(73);
            Field field74 = new Field(74);
            Field field75 = new Field(75);
            Field field76 = new Field(76);
            Field field77 = new Field(77);
            Field field78 = new Field(78);
            Field field79 = new Field(79);
            Field field80 = new Field(80);
            Field field81 = new Field(81);

            List<Field> fields = new List<Field>();
            fields.Add(field1);
            fields.Add(field2);
            fields.Add(field3);
            fields.Add(field4);
            fields.Add(field5);
            fields.Add(field6);
            fields.Add(field7);
            fields.Add(field8);
            fields.Add(field9);
            fields.Add(field10);
            fields.Add(field11);
            fields.Add(field12);
            fields.Add(field13);
            fields.Add(field14);
            fields.Add(field15);
            fields.Add(field16);
            fields.Add(field17);
            fields.Add(field18);
            fields.Add(field19);
            fields.Add(field20);
            fields.Add(field21);
            fields.Add(field22);
            fields.Add(field23);
            fields.Add(field24);
            fields.Add(field25);
            fields.Add(field26);
            fields.Add(field27);
            fields.Add(field28);
            fields.Add(field29);
            fields.Add(field30);
            fields.Add(field31);
            fields.Add(field32);
            fields.Add(field33);
            fields.Add(field34);
            fields.Add(field35);
            fields.Add(field36);
            fields.Add(field37);
            fields.Add(field38);
            fields.Add(field39);
            fields.Add(field40);
            fields.Add(field41);
            fields.Add(field42);
            fields.Add(field43);
            fields.Add(field44);
            fields.Add(field45);
            fields.Add(field46);
            fields.Add(field47);
            fields.Add(field48);
            fields.Add(field49);
            fields.Add(field50);
            fields.Add(field51);
            fields.Add(field52);
            fields.Add(field53);
            fields.Add(field54);
            fields.Add(field55);
            fields.Add(field56);
            fields.Add(field57);
            fields.Add(field58);
            fields.Add(field59);
            fields.Add(field60);
            fields.Add(field61);
            fields.Add(field62);
            fields.Add(field63);
            fields.Add(field64);
            fields.Add(field65);
            fields.Add(field66);
            fields.Add(field67);
            fields.Add(field68);
            fields.Add(field69);
            fields.Add(field70);
            fields.Add(field71);
            fields.Add(field72);
            fields.Add(field73);
            fields.Add(field74);
            fields.Add(field75);
            fields.Add(field76);
            fields.Add(field77);
            fields.Add(field78);
            fields.Add(field79);
            fields.Add(field80);
            fields.Add(field81);
            mainViewModel.SetFields(fields);

            FieldContainer row1 = new FieldContainer(field1, field2, field3, field4, field5, field6, field7, field8, field9);
            FieldContainer row2 = new FieldContainer(field10, field11, field12, field13, field14, field15, field16, field17, field18);
            FieldContainer row3 = new FieldContainer(field19, field20, field21, field22, field23, field24, field25, field26, field27);
            FieldContainer row4 = new FieldContainer(field28, field29, field30, field31, field32, field33, field34, field35, field36);
            FieldContainer row5 = new FieldContainer(field37, field38, field39, field40, field41, field42, field43, field44, field45);
            FieldContainer row6 = new FieldContainer(field46, field47, field48, field49, field50, field51, field52, field53, field54);
            FieldContainer row7 = new FieldContainer(field55, field56, field57, field58, field59, field60, field61, field62, field63);
            FieldContainer row8 = new FieldContainer(field64, field65, field66, field67, field68, field69, field70, field71, field72);
            FieldContainer row9 = new FieldContainer(field73, field74, field75, field76, field77, field78, field79, field80, field81);

            FieldContainer column1 = new FieldContainer(field1, field10, field19, field28, field37, field46, field55, field64, field73);
            FieldContainer column2 = new FieldContainer(field2, field11, field20, field29, field38, field47, field56, field65, field74);
            FieldContainer column3 = new FieldContainer(field3, field12, field21, field30, field39, field48, field57, field66, field75);
            FieldContainer column4 = new FieldContainer(field4, field13, field22, field31, field40, field49, field58, field67, field76);
            FieldContainer column5 = new FieldContainer(field5, field14, field23, field32, field41, field50, field59, field68, field77);
            FieldContainer column6 = new FieldContainer(field6, field15, field24, field33, field42, field51, field60, field69, field78);
            FieldContainer column7 = new FieldContainer(field7, field16, field25, field34, field43, field52, field61, field70, field79);
            FieldContainer column8 = new FieldContainer(field8, field17, field26, field35, field44, field53, field62, field71, field80);
            FieldContainer column9 = new FieldContainer(field9, field18, field27, field36, field45, field54, field63, field72, field81);

            FieldContainer square1 = new FieldContainer(field1, field2, field3, field10, field11, field12, field19, field20, field21);
            FieldContainer square2 = new FieldContainer(field4, field5, field6, field13, field14, field15, field22, field23, field24);
            FieldContainer square3 = new FieldContainer(field7, field8, field9, field16, field17, field18, field25, field26, field27);
            FieldContainer square4 = new FieldContainer(field28, field29, field30, field37, field38, field39, field46, field47, field48);
            FieldContainer square5 = new FieldContainer(field31, field32, field33, field40, field41, field42, field49, field50, field51);
            FieldContainer square6 = new FieldContainer(field34, field35, field36, field43, field44, field45, field52, field53, field54);
            FieldContainer square7 = new FieldContainer(field55, field56, field57, field64, field65, field66, field73, field74, field75);
            FieldContainer square8 = new FieldContainer(field58, field59, field60, field67, field68, field69, field76, field77, field78);
            FieldContainer square9 = new FieldContainer(field61, field62, field63, field70, field71, field72, field79, field80, field81);
            List<FieldContainer> fieldContainers = new List<FieldContainer>();
            fieldContainers.Add(row1);
            fieldContainers.Add(row2);
            fieldContainers.Add(row3);
            fieldContainers.Add(row4);
            fieldContainers.Add(row5);
            fieldContainers.Add(row6);
            fieldContainers.Add(row7);
            fieldContainers.Add(row8);
            fieldContainers.Add(row9);
            fieldContainers.Add(column1);
            fieldContainers.Add(column2);
            fieldContainers.Add(column3);
            fieldContainers.Add(column4);
            fieldContainers.Add(column5);
            fieldContainers.Add(column6);
            fieldContainers.Add(column7);
            fieldContainers.Add(column8);
            fieldContainers.Add(column9);
            fieldContainers.Add(square1);
            fieldContainers.Add(square2);
            fieldContainers.Add(square3);
            fieldContainers.Add(square4);
            fieldContainers.Add(square5);
            fieldContainers.Add(square6);
            fieldContainers.Add(square7);
            fieldContainers.Add(square8);
            fieldContainers.Add(square9);

            mainViewModel.Solver.SetContainers(fieldContainers);
        }


    }
}
